# Generated by Django 3.0.5 on 2020-04-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.AddField(
            model_name='content',
            name='embed_html',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='content',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
