# Generated by Django 3.0.5 on 2020-04-20 18:09

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200420_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='embed_html',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.Content.get_image_path),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='content',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
