# Generated by Django 3.0.5 on 2020-04-24 11:35

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200420_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='thumbnail',
            field=models.ImageField(upload_to=main.models.Content.get_image_path),
        ),
    ]
