# Generated by Django 3.0.5 on 2020-04-27 13:30

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200425_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
