# Generated by Django 3.0.5 on 2020-04-29 04:29

from django.db import migrations, models
import main.models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200427_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('scratch', 'Scratch'), ('unity', 'Unity'), ('web', 'Web'), ('artwork3d', '3D Artwork'), ('artwork2d', '2D Artwork'), ('other', 'Other')], default='scratch', max_length=32, verbose_name='コンテンツの種類'),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='説明文'),
        ),
        migrations.AlterField(
            model_name='content',
            name='thumbnail',
            field=models.ImageField(upload_to=main.models.Content.get_image_path, verbose_name='トップ画像'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=64, verbose_name='作品タイトル'),
        ),
        migrations.AlterField(
            model_name='content',
            name='url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='作品の掲載元のURL'),
        ),
    ]
