# Generated by Django 3.0.5 on 2020-04-29 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20200429_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('remote_addr', models.GenericIPAddressField(verbose_name='接続元IPアドレス')),
                ('user_agent', models.TextField(verbose_name='接続元UserAgent')),
                ('request_method', models.CharField(max_length=10, verbose_name='HTTPメソッド')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='main.Content')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
