# Generated by Django 3.0.5 on 2020-04-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200428_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.TextField(blank=True, default='', max_length=140, null=True, verbose_name='自己紹介文'),
        ),
    ]
